### This file was generated by Nexus Schema
### Do not make changes to this file directly

type Artwork {
  description: String!
  handle: String!
  id: ID!
  kind: String!
  owner: User
  price: Int
  type: String
}

"""
The `BigInt` scalar type represents non-fractional signed whole numeric values.
@see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
"""
scalar BigInt

"""
The `Byte` scalar type represents byte value as a Buffer
"""
scalar Bytes

type ClientError {
  given: String!
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

"""
An arbitrary-precision Decimal type
"""
scalar Decimal

"""
The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar Json
  @specifiedBy(
    url: "http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf"
  )

type Query {
  """
  This query accepts a boolean argument whether to filter only for auctions or not
  """
  listArtworks(auction: Boolean): [Artwork!]!
}

type User {
  hiii: String!
  id: String!
  test: String!
}
