name: Deploy to Production
on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:latest
    name: Tests
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: hashtune
          POSTGRES_PORT: 5432
          POSTGRES_USER: hashtune
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
      - run: yarn install
      - run: yarn ci:prisma:migrate
        env:
          DATABASE_URL: postgresql://hashtune:hashtune@postgres:5432/postgres
      - run: yarn ci:prisma:generate
        env:
          DATABASE_URL: postgresql://hashtune:hashtune@postgres:5432/postgres
      - run: yarn test:api
        env:
          DATABASE_URL: postgresql://hashtune:hashtune@postgres:5432/postgres

  migrate:
    name: Migrate Production DB
    needs: tests
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hashtune-server
      PROJECT_ID: se36-cloud-computing

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Get Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Database Migration
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: |
          yarn install
          ./cloud_sql_proxy -dir=/cloudsql -instances=se36-cloud-computing:europe-west1:prod-db=tcp:5432 & sleep 10s && yarn prisma migrate deploy && yarn prisma generate

  deploy-image:
    name: Deploy Latest Image to Production on Cloud Run
    needs: migrate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Google Cloud Run
        id: deploy-run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: hashtune-server
          image: europe-west1-docker.pkg.dev/se36-cloud-computing/hashtune/hashtune-server:latest
          region: europe-west1
          flags: --allow-unauthenticated
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
