name: Hashtune Server Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_SECRET: ${{secrets.SERVER_SECRET}}
      STAGE: production
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            rm -rf Hashtune-Marketplace-Server
            git clone git@github.com:hashtune/Hashtune-Marketplace-Server.git
            cd Hashtune-Marketplace-Server
            yarn
            pm2 delete server
            yarn prisma:deploy
            yarn prisma:generate
            npx tsc
            pm2 start dist/graphql/server.js --name "server" -- start
            echo 'Succesfully deployed 🎉'
