name: Hashtune Server Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean  
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
     
          script: |
            rm -rf Hashtune-Marketplace-Server
            git clone git@github.com:hashtune/Hashtune-Marketplace-Server.git
            cd Hashtune-Marketplace-Server
            yarn
            npx tsc
            pm2 kill
            pm2 start dist/graphql/server.js
            echo 'Succesfully deployed 🎉'