name: Deploy to Staging
on:
  push:

jobs:
  migrate:
    name: migrate db
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hashtune-server-staging
      PROJECT_ID: se36-cloud-computing

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Get Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Database Migration
        env:
          DATABASE_URL: ${{secrets.STAGING_DATABASE_URL}}
        run: |
          yarn install
          ./cloud_sql_proxy -dir=/cloudsql -instances=se36-cloud-computing:europe-west1:staging-db=tcp:5432 & sleep 10s && yarn prisma migrate deploy && yarn prisma generate

  # deploy-image:
  #   name: Deploy Image to cloud run
  #   needs: migrate
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Deploy to Google Cloud Run
  #       id: deploy-run
  #       uses: google-github-actions/deploy-cloudrun@v0
  #       with:
  #         service: hashtune-server-staging
  #         image: europe-west1-docker.pkg.dev/se36-cloud-computing/hashtune/hashtune-server:latest
  #         region: europe-west1
  #         flags: --allow-unauthenticated
  #         credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
