name: Build Container and Deploy
on:
  push:
    branches: [main, build/deployment-config]

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
  
  push-image:
    name: Push image to artifact registry
    needs: build-image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hashtune-server
      PROJECT_ID: se36-cloud-computing

      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Tag Image
        id: assign_image_tag
        run: |
          bash ./assign_image_tag.sh -v minor
      
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.assign_image_tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

  # migrate:
  #   name: migrate db
  #   runs-on: ubuntu-latest
  #   env:
  #     IMAGE_NAME: hashtune-server
  #     PROJECT_ID: se36-cloud-computing
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - uses: google-github-actions/setup-gcloud@main
  #       with:
  #         service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  #         project_id: ${{ env.PROJECT_ID }}
  #         export_default_credentials: true

  #     - uses: mattes/gce-cloudsql-proxy-action@v1
  #       with:
  #         creds: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  #         instance: se36-cloud-computing:europe-west1:prod-db

  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'  

  #     - name: Database Migration
  #       env:
  #         DATABASE_URL: ${{secrets.DATABASE_URL}}
  #       run: |
  #         yarn install --frozen-lockfile
  #         yarn prisma migrate deploy
  #         yarn prisma generate
