# Initial boilerplate for Deployment
# name: Hashtune's Server CD

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     timeout-minutes: 20
#     env:
#       DATABASE_URL: ${{ secrets.DATABASE_URL }}
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 14.x
#           cache: 'yarn'
#       - run: yarn docker:up
#       - run: yarn